# Generated by Django 3.0.6 on 2020-05-07 14:28

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, default='', verbose_name='GitHub')),
                ('telegram_nick', models.TextField(blank=True, default='', verbose_name='Telegram')),
                ('discord_nick', models.TextField(blank=True, default='', verbose_name='Discord')),
                ('bio', models.TextField(default='', help_text='Descreva sobre você para os amiginhos poderem te conhecer melhor!!', verbose_name='Sobre você')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Tag')),
                ('color', colorful.fields.RGBColorField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500, verbose_name='Nome do grupo')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('discord', models.URLField(blank=True, default='', verbose_name='Discord')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('users', models.ManyToManyField(blank=True, to='core.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
