# Generated by Django 3.0.6 on 2020-05-07 17:06

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyroom',
            old_name='discord',
            new_name='discord_group',
        ),
        migrations.RenameField(
            model_name='studyroom',
            old_name='tags',
            new_name='tags_group',
        ),
        migrations.RenameField(
            model_name='studyroom',
            old_name='telegram',
            new_name='telegram_group',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='users',
        ),
        migrations.AddField(
            model_name='studyroom',
            name='limit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data expiracao do Grupo'),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='users_group',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
